package_assets: on
template_function: Hogan.compile
gzip_assets: off
compress_assets: off
embed_assets: off

javascripts:
    hw:
        - public/js/lib/date.js
        - public/js/lib/jquery-1.7.1.min.js
        - public/js/lib/underscore.js
        - public/js/lib/backbone.js
        - public/js/lib/hogan-1.0.5.js
        - public/js/lib/leaflet.js
        - public/js/hw.js
        - src/templates/*.jst
    
stylesheets:
    hw:
        - public/css/bootstrap.css
        - public/css/leaflet.css
        - public/css/style.css
    
    hw.ie:
        - public/css/leaflet.ie.css

coffee:
    - src/models.coffee
    - src/collections.coffee
    - src/views/*.coffee
